const PLANT_SCIENTIFIC = [
  "Pilea cadierei",
  "Anthurium clarinervium",
  "Dypsis lutescens",
  "Syngonium podophyllum" ,
  "Asparagus densiflorus 'Sprengeri'" ,
  "Peperomia obtusifolia" ,
  "Soleirolia soleirolii" ,
  "Asplenium nidus" ,
  "Philodendron erubscens",
  "Nephrolepsis exaltata" ,
  "Pteris cretica",
  "Pellaea rotundifolia",
  "Caladium x hortulanum" ,
  "Calathea orbifolia",
  "Calathea ornata" ,
  "Calathea lancifolia" ,
  "Calathea roseopicta 'Corona'",
  "Darlingtonia californica",
  "Drosera capensis",
  "Zamia furfuracea",
  "Aspidistra elatior",
  "Chamaedorea cataractarum",
  "Radermachera sinica" ,
  "Aglaonema commutatum",
  "Pilea peperomioides" ,
  "Selaginella kraussiana",
  "Coffea arabica",
  "Coleus blumei" ,
  "Acalypha wilkesiana" ,
  "Nertera granadensis" ,
  "Dracaena fragrans" ,
  "Ficus pumila",
  "Codiaeum variegatum" ,
  "Dracaena marginata",
  "Dieffenbachia" ,
  "Alocasia amazonica",
  "Hedera helix",
  "Chamaerops humilis",
  "Dizygotheca elegantissima" ,
  "Isolepis cernua" ,
  "Ficus binnendiijkii 'Alii'",
  "Ficus lyrata",
  "Chlorophytum orchidastrum" ,
  "Caryota mitis" ,
  "Asparagus densiflorus 'Myers'" ,
  "Pilea involucrata" ,
  "Aucuba japonica" ,
  "Cissus rhombifolia",
  "Philodendron scandens" ,
  "Cyrtomium falcatum",
  "Tradescantia zebrina",
  "Iresine herbstii",
  "Begonia masoniana" ,
  "Dracaena deremensis" ,
  "Fatsia japonica" ,
  "Solanum pseudocapsicum",
  "Juncus effusus 'Spiralis'" ,
  "Howea forsteriana" ,
  "Rhapis excelsa",
  "Dracaena sanderiana" ,
  "Adiantum",
  "Polyscias fruticosa" ,
  "Pachira aquatica",
  "Monstera adansonii",
  "Tradescantia spathacea",
  "Muehlenbeckia complexa",
  "Fittonia verschaffeltii" ,
  "Araucaria heterophylla",
  "Capsicum annuum" ,
  "Cyperus papyrus" ,
  "Chamaedorea elegans" ,
  "Calathea makoyana" ,
  "Peperomia caperata",
  "Strobilanthes dyerianus" ,
  "Philodendron hybrid" ,
  "Philodendron hederaceum 'Brasil'",
  "Philodendron hederaceum hybrid",
  "Philodendron hybrid" ,
  "Tolmiea menziesii" ,
  "Nepenthes hybrids" ,
  "Dracaena reflexa",
  "Hypoestes phyllostachya" ,
  "Epipremnum aureum" ,
  "Maranta leuconeura",
  "Tradescantia pallida",
  "Gynura aurantiaca" ,
  "Sarracenia purpurea" ,
  "Phoenix roebelenii",
  "Davallia fejeensis",
  "Begonia rex" ,
  "Ceropegia woodii",
  "Ficus elastica",
  "Cycas revoluta",
  "Scindapsus pictus" ,
  "Schefflera spp." ,
  "Pandanus veitchii" ,
  "Mimosa pudica" ,
  "Breynia nivosa",
  "Chlorophytum comosum",
  "Philodendron bipinnatifidum" ,
  "Platycerium bifurcatum",
  "Saxifraga stolonifera" ,
  "Stromanthe sanguinea",
  "Drosera rotundifolia",
  "Plectranthus species",
  "Ipomea batatas",
  "Monstera deliciosa",
  "Cordyline terminalis",
  "Ficus triangularis",
  "Dionaea muscipula" ,
  "Peperomia argyreia",
  "Ficus benjamina" ,
  "Trachycarpus fortunei" ,
  "Aphelandra squarrosa",
  "Zamioculcas zamiifolia",
  "Achimenes hybrids" ,
  "Agapanthus africanus",
  "Saintpaulia" ,
  "Tillandsia ionantha" ,
  "Hippeastrum hybrids" ,
  "Eucharis x grandiflora",
  "Brugmansia x candida",
  "Begonia x corallina" ,
  "Anthurium andraeanum",
  "Rhododendron simsii" ,
  "Michelia figo" ,
  "Tacca chantrieri",
  "Begonia x hiemalis",
  "Strelitzia reginae",
  "Clerodendrum thomsoniae" ,
  "Scadoxus multiflorus",
  "Callistemon citrinus",
  "Bougainvillea glabra",
  "Justicia carnea" ,
  "Camellia japonica" ,
  "Campanula isophylla" ,
  "Manettia inflata",
  "Streptocarpus hybrids" ,
  "Celosia argentea var. plumosa" ,
  "Cuphea ignea",
  "Senecio hybrids" ,
  "Clivia miniata",
  "Ardisia crenata" ,
  "Crocus hybrids",
  "Cyclamen persicum" ,
  "Narcissus spp.",
  "Begonia hybrids" ,
  "Iridaceae x hollandica",
  "Acalypha pendula",
  "Iris reticulata" ,
  "Lilium longiflorum",
  "Crossandra infundibuliformis",
  "Russelia equisetiformis" ,
  "Episcia cupreata",
  "Anthurium scherzerianum" ,
  "Chrysanthemum morifolium",
  "Abutilon hybrids",
  "Freesia hybrids" ,
  "Fuchsia hybrids" ,
  "Gardenia jasminoides",
  "Pelargonium x hortorum",
  "Gerbera jamesonii" ,
  "Gloriosa superba",
  "Sinningia speciosa hybrids",
  "Musella lasiocarpa",
  "Pachystachys lutea",
  "Allamanda cathartica",
  "Columnea hybrids",
  "Muscari spp.",
  "Heliconia psittacorum" ,
  "Helleborus niger",
  "Hibiscus rosa-sinensis",
  "Hyacinthus orientalis hybrids" ,
  "Hydrangea macrophylla" ,
  "Impatiens hybrids" ,
  "Pelargonium peltatum",
  "Ixora coccinea",
  "Jasminum polyanthum" ,
  "Kohleria",
  "Lantana camara",
  "Convallaria majalis" ,
  "Aeschynanthus lobbianus" ,
  "Stephanotis floribunda",
  "Mandevilla hybrids",
  "Pelargonium domesticum",
  "Medinilla magnifica" ,
  "Rosa chinensis hybrids",
  "Plectranthus hybrid" ,
  "Impatiens x hawkeri hybrid",
  "Nerium oleander" ,
  "Viola x wittrockiana",
  "Narcissus jonquilla" ,
  "Passiflora caerulea" ,
  "Spathiphyllum" ,
  "Catharanthus roseus" ,
  "Exacum affine" ,
  "Eucomis comosa",
  "Zantedeschia rehmannii",
  "Tillandsia cyanea" ,
  "Plumeria rubra",
  "Calceolaria herbeohybrida" ,
  "Euphorbia pulcherrima" ,
  "Calliandra haematocephala" ,
  "Primula hybrids" ,
  "Oxalis regnellii",
  "Billbergia nutans" ,
  "Alpinia purpurata" ,
  "Lycoris radiata" ,
  "Guzmania lingulata",
  "Pelargonium species and hybrids" ,
  "Oxalis species",
  "Justicia brandegeana",
  "Curcuma alismatifolia" ,
  "Antirrinum majus",
  "Hymenocallis littoralis" ,
  "Tulipa hybrids",
  "Aechmea fasciata",
  "Neomarica spp.",
  "Begonia x semperflorens-cultorum",
  "Hoya carnosa",
  "Aloe barbadensis",
  "Agave parryi",
  "Cactaceae family",
  "Schlumbergera hybrids" ,
  "Euphorbia milii" ,
  "Sansevieria cylindrica",
  "Adenium obesum",
  "Sedum morganianum" ,
  "Hatiora gaertneri" ,
  "Echeveria species" ,
  "Kalanchoe blossfeldiana" ,
  "Gasteria Sp.",
  "Haworthia species" ,
  "Hoya kerrii" ,
  "Crassula ovata",
  "Lithops species" ,
  "Pachypodium lamerei" ,
  "Rhipsalis baccifera" ,
  "Sansevieria trifasciata" ,
  "Kalanchoe daigremontiana",
  "Epiphyllum species and hybrids",
  "Kalanchoe thyrsiflora" ,
  "Kalanchoe tomentosa" ,
  "Beaucarnea recurvata",
  "Senecio radicans",
  "Senecio rowleyanus",
  "Ceropegia woodii",
  "Sedum rubrotinctum",
  "Schlumbergera truncata",
  "Faucaria tigrina",
  "Yucca elephantipes",
]

const PLANT_IMAGE = {
  "isolepis-cernua": "isolepis-cernua.jpg",
  "ficus-binnendiijkii-'alii'": "ficus-binnendiijkii-'alii'.JPG",
  "gardenia-jasminoides": "gardenia-jasminoides.jpg",
  "aglaonema-commutatum": "aglaonema-commutatum.jpg",
  "dracaena-fragrans": "dracaena-fragrans.jpg",
  "justicia-brandegeana": "justicia-brandegeana.jpg",
  "gerbera-jamesonii": "gerbera-jamesonii.jpg",
  "sedum-morganianum": "sedum-morganianum.jpg",
  "agapanthus-africanus": "agapanthus-africanus.JPG",
  "tradescantia-pallida": "tradescantia-pallida.jpg",
  "acalypha-wilkesiana": "acalypha-wilkesiana.jpg",
  "neomarica-spp.": "neomarica-spp..jpg",
  "cyrtomium-falcatum": "cyrtomium-falcatum.jpg",
  "haworthia-species": "haworthia-species.jpg",
  "solanum-pseudocapsicum": "solanum-pseudocapsicum.jpg",
  "strelitzia-reginae": "strelitzia-reginae.jpg",
  "senecio-hybrids": "senecio-hybrids.jpg",
  "convallaria-majalis": "convallaria-majalis.jpg",
  "dieffenbachia": "dieffenbachia.jpg",
  "calathea-ornata": "calathea-ornata.jpg",
  "antirrinum-majus": "antirrinum-majus.jpg",
  "crossandra-infundibuliformis": "crossandra-infundibuliformis.JPG",
  "faucaria-tigrina": "faucaria-tigrina.jpg",
  "justicia-carnea": "justicia-carnea.JPG",
  "scindapsus-pictus": "scindapsus-pictus.jpg",
  "clivia-miniata": "clivia-miniata.jpg",
  "nepenthes-hybrids": "nepenthes-hybrids.jpg",
  "zamia-furfuracea": "zamia-furfuracea.jpg",
  "davallia-fejeensis": "davallia-fejeensis.jpg",
  "capsicum-annuum": "capsicum-annuum.jpg",
  "gloriosa-superba": "gloriosa-superba.jpg",
  "philodendron-erubscens": "philodendron-erubscens.jpg",
  "zantedeschia-rehmannii": "zantedeschia-rehmannii.jpg",
  "ipomea-batatas": "ipomea-batatas.jpg",
  "lycoris-radiata": "lycoris-radiata.jpg",
  "ixora-coccinea": "ixora-coccinea.jpg",
  "radermachera-sinica": "radermachera-sinica.jpg",
  "coffea-arabica": "coffea-arabica.jpg",
  "tillandsia-ionantha": "tillandsia-ionantha.jpg",
  "ficus-triangularis": "ficus-triangularis.jpg",
  "syngonium-podophyllum": "syngonium-podophyllum.jpg",
  "hippeastrum-hybrids": "hippeastrum-hybrids.jpg",
  "dracaena-reflexa": "dracaena-reflexa.JPG",
  "plumeria-rubra": "plumeria-rubra.jpg",
  "impatiens-x-hawkeri-hybrid": "impatiens-x-hawkeri-hybrid.jpg",
  "drosera-capensis": "drosera-capensis.jpg",
  "achimenes-hybrids": "achimenes-hybrids.jpg",
  "pachira-aquatica": "pachira-aquatica.jpg",
  "schlumbergera-truncata": "schlumbergera-truncata.jpg",
  "anthurium-andraeanum": "anthurium-andraeanum.jpg",
  "euphorbia-milii": "euphorbia-milii.jpg",
  "catharanthus-roseus": "catharanthus-roseus.jpg",
  "freesia-hybrids": "freesia-hybrids.jpg",
  "yucca-elephantipes": "yucca-elephantipes.jpg",
  "tolmiea-menziesii": "tolmiea-menziesii.jpg",
  "dracaena-deremensis": "dracaena-deremensis.jpg",
  "sansevieria-trifasciata": "sansevieria-trifasciata.jpg",
  "rosa-chinensis-hybrids": "rosa-chinensis-hybrids.jpg",
  "impatiens-hybrids": "impatiens-hybrids.jpg",
  "schefflera-spp.": "schefflera-spp..jpg",
  "pelargonium-domesticum": "pelargonium-domesticum.JPG",
  "agave-parryi": "agave-parryi.jpg",
  "gasteria-sp.": "gasteria-sp..jpg",
  "selaginella-kraussiana": "selaginella-kraussiana.jpg",
  "monstera-deliciosa": "monstera-deliciosa.jpg",
  "guzmania-lingulata": "guzmania-lingulata.JPG",
  "lilium-longiflorum": "lilium-longiflorum.jpg",
  "calathea-orbifolia": "calathea-orbifolia.jpg",
  "pelargonium-x-hortorum": "pelargonium-x-hortorum.jpg",
  "curcuma-alismatifolia": "curcuma-alismatifolia.jpg",
  "nephrolepsis-exaltata": "nephrolepsis-exaltata.jpg",
  "asplenium-nidus": "asplenium-nidus.jpg",
  "codiaeum-variegatum": "codiaeum-variegatum.jpg",
  "camellia-japonica": "camellia-japonica.jpg",
  "strobilanthes-dyerianus": "strobilanthes-dyerianus.jpg",
  "tulipa-hybrids": "tulipa-hybrids.jpg",
  "kohleria": "kohleria.jpg",
  "dionaea-muscipula": "dionaea-muscipula.jpg",
  "muscari-spp.": "muscari-spp..jpg",
  "campanula-isophylla": "campanula-isophylla.JPG",
  "michelia-figo": "michelia-figo.jpg",
  "muehlenbeckia-complexa": "muehlenbeckia-complexa.jpg",
  "billbergia-nutans": "billbergia-nutans.JPG",
  "saxifraga-stolonifera": "saxifraga-stolonifera.jpg",
  "hyacinthus-orientalis-hybrids": "hyacinthus-orientalis-hybrids.JPG",
  "caladium-x-hortulanum": "caladium-x-hortulanum.jpg",
  "philodendron-hederaceum-'brasil'": "philodendron-hederaceum-'brasil'.JPG",
  "hypoestes-phyllostachya": "hypoestes-phyllostachya.jpg",
  "bougainvillea-glabra": "bougainvillea-glabra.jpg",
  "jasminum-polyanthum": "jasminum-polyanthum.jpg",
  "phoenix-roebelenii": "phoenix-roebelenii.jpg",
  "stromanthe-sanguinea": "stromanthe-sanguinea.jpg",
  "soleirolia-soleirolii": "soleirolia-soleirolii.JPG",
  "pilea-cadierei": "pilea-cadierei.jpg",
  "medinilla-magnifica": "medinilla-magnifica.jpg",
  "dypsis-lutescens": "dypsis-lutescens.jpg",
  "exacum-affine": "exacum-affine.jpg",
  "philodendron-hederaceum-hybrid": "philodendron-hederaceum-hybrid.jpg",
  "aspidistra-elatior": "aspidistra-elatior.jpg",
  "tradescantia-zebrina": "tradescantia-zebrina.jpg",
  "calathea-lancifolia": "calathea-lancifolia.jpeg",
  "schlumbergera-hybrids": "schlumbergera-hybrids.jpg",
  "iris-reticulata": "iris-reticulata.jpg",
  "aeschynanthus-lobbianus": "aeschynanthus-lobbianus.JPG",
  "mandevilla-hybrids": "mandevilla-hybrids.jpg",
  "kalanchoe-daigremontiana": "kalanchoe-daigremontiana.jpg",
  "breynia-nivosa": "breynia-nivosa.jpg",
  "adiantum": "adiantum.jpg",
  "celosia-argentea-var.-plumosa": "celosia-argentea-var.-plumosa.JPG",
  "gynura-aurantiaca": "gynura-aurantiaca.jpg",
  "philodendron-hybrid": "philodendron-hybrid.jpg",
  "senecio-radicans": "senecio-radicans.jpg",
  "fuchsia-hybrids": "fuchsia-hybrids.jpg",
  "senecio-rowleyanus": "senecio-rowleyanus.jpg",
  "hibiscus-rosa-sinensis": "hibiscus-rosa-sinensis.jpg",
  "monstera-adansonii": "monstera-adansonii.jpg",
  "begonia-x-semperflorens-cultorum": "begonia-x-semperflorens-cultorum.jpg",
  "dracaena-sanderiana": "dracaena-sanderiana.jpg",
  "anthurium-scherzerianum": "anthurium-scherzerianum.jpg",
  "begonia-masoniana": "begonia-masoniana.jpg",
  "cissus-rhombifolia": "cissus-rhombifolia.jpg",
  "eucharis-x-grandiflora": "eucharis-x-grandiflora.jpg",
  "peperomia-obtusifolia": "peperomia-obtusifolia.JPG",
  "chamaedorea-elegans": "chamaedorea-elegans.jpg",
  "asparagus-densiflorus-'sprengeri'": "asparagus-densiflorus-'sprengeri'.jpg",
  "ardisia-crenata": "ardisia-crenata.JPG",
  "ficus-lyrata": "ficus-lyrata.jpg",
  "pilea-peperomioides": "pilea-peperomioides.jpg",
  "begonia-x-corallina": "begonia-x-corallina.JPG",
  "ceropegia-woodii": "ceropegia-woodii.JPG",
  "sinningia-speciosa-hybrids": "sinningia-speciosa-hybrids.jpg",
  "aphelandra-squarrosa": "aphelandra-squarrosa.jpg",
  "pelargonium-peltatum": "pelargonium-peltatum.jpg",
  "hatiora-gaertneri": "hatiora-gaertneri.jpg",
  "eucomis-comosa": "eucomis-comosa.jpg",
  "asparagus-densiflorus-'myers'": "asparagus-densiflorus-'myers'.jpg",
  "ficus-pumila": "ficus-pumila.jpg",
  "tacca-chantrieri": "tacca-chantrieri.jpg",
  "euphorbia-pulcherrima": "euphorbia-pulcherrima.jpg",
  "pelargonium-species-and-hybrids": "pelargonium-species-and-hybrids.jpg",
  "sedum-rubrotinctum": "sedum-rubrotinctum.jpg",
  "narcissus-jonquilla": "narcissus-jonquilla.jpg",
  "philodendron-scandens": "philodendron-scandens.jpg",
  "pilea-involucrata": "pilea-involucrata.JPG",
  "calliandra-haematocephala": "calliandra-haematocephala.jpg",
  "cuphea-ignea": "cuphea-ignea.jpg",
  "nertera-granadensis": "nertera-granadensis.JPG",
  "iresine-herbstii": "iresine-herbstii.jpg",
  "coleus-blumei": "coleus-blumei.jpg",
  "beaucarnea-recurvata": "beaucarnea-recurvata.jpg",
  "drosera-rotundifolia": "drosera-rotundifolia.JPG",
  "hydrangea-macrophylla": "hydrangea-macrophylla.jpg",
  "juncus-effusus-'spiralis'": "juncus-effusus-'spiralis'.jpg",
  "dizygotheca-elegantissima": "dizygotheca-elegantissima.jpg",
  "lantana-camara": "lantana-camara.JPG",
  "calceolaria-herbeohybrida": "calceolaria-herbeohybrida.jpg",
  "crassula-ovata": "crassula-ovata.jpg",
  "araucaria-heterophylla": "araucaria-heterophylla.jpg",
  "saintpaulia": "saintpaulia.jpg",
  "tradescantia-spathacea": "tradescantia-spathacea.jpg",
  "peperomia-caperata": "peperomia-caperata.jpg",
  "anthurium-clarinervium": "anthurium-clarinervium.jpg",
  "maranta-leuconeura": "maranta-leuconeura.jpg",
  "heliconia-psittacorum": "heliconia-psittacorum.jpg",
  "clerodendrum-thomsoniae": "clerodendrum-thomsoniae.jpg",
  "viola-x-wittrockiana": "viola-x-wittrockiana.JPG",
  "fittonia-verschaffeltii": "fittonia-verschaffeltii.jpg",
  "rhododendron-simsii": "rhododendron-simsii.jpg",
  "philodendron-bipinnatifidum": "philodendron-bipinnatifidum.jpg",
  "chamaedorea-cataractarum": "chamaedorea-cataractarum.JPG",
  "platycerium-bifurcatum": "platycerium-bifurcatum.jpg",
  "scadoxus-multiflorus": "scadoxus-multiflorus.jpg",
  "caryota-mitis": "caryota-mitis.jpg",
  "oxalis-regnellii": "oxalis-regnellii.jpg",
  "abutilon-hybrids": "abutilon-hybrids.jpg",
  "rhapis-excelsa": "rhapis-excelsa.JPG",
  "mimosa-pudica": "mimosa-pudica.JPG",
  "ficus-benjamina": "ficus-benjamina.jpg",
  "columnea-hybrids": "columnea-hybrids.jpg",
  "cycas-revoluta": "cycas-revoluta.jpg",
  "chamaerops-humilis": "chamaerops-humilis.jpg",
  "chlorophytum-comosum": "chlorophytum-comosum.jpg",
  "stephanotis-floribunda": "stephanotis-floribunda.jpg",
  "kalanchoe-blossfeldiana": "kalanchoe-blossfeldiana.JPG",
  "cyclamen-persicum": "cyclamen-persicum.jpg",
  "episcia-cupreata": "episcia-cupreata.jpg",
  "hedera-helix": "hedera-helix.jpg",
  "aechmea-fasciata": "aechmea-fasciata.JPG",
  "calathea-makoyana": "calathea-makoyana.jpg",
  "russelia-equisetiformis": "russelia-equisetiformis.jpg",
  "cactaceae-family": "cactaceae-family.jpg",
  "dracaena-marginata": "dracaena-marginata.jpg",
  "howea-forsteriana": "howea-forsteriana.jpg",
  "aloe-barbadensis": "aloe-barbadensis.jpg",
  "cyperus-papyrus": "cyperus-papyrus.PNG",
  "streptocarpus-hybrids": "streptocarpus-hybrids.jpg",
  "epiphyllum-species-and-hybrids": "epiphyllum-species-and-hybrids.jpg",
  "alocasia-amazonica": "alocasia-amazonica.jpg",
  "lithops-species": "lithops-species.jpg",
  "darlingtonia-californica": "darlingtonia-californica.jpg",
  "polyscias-fruticosa": "polyscias-fruticosa.jpg",
  "epipremnum-aureum": "epipremnum-aureum.jpg",
  "spathiphyllum": "spathiphyllum.jpg",
  "passiflora-caerulea": "passiflora-caerulea.jpg",
  "sarracenia-purpurea": "sarracenia-purpurea.jpg",
  "pachypodium-lamerei": "pachypodium-lamerei.jpg",
  "chlorophytum-orchidastrum": "chlorophytum-orchidastrum.jpg",
  "kalanchoe-tomentosa": "kalanchoe-tomentosa.jpg",
  "plectranthus-species": "plectranthus-species.jpg",
  "chrysanthemum-morifolium": "chrysanthemum-morifolium.jpg",
  "hymenocallis-littoralis": "hymenocallis-littoralis.JPG",
  "begonia-rex": "begonia-rex.jpg",
  "pteris-cretica": "pteris-cretica.jpg",
  "aucuba-japonica": "aucuba-japonica.jpg",
  "zamioculcas-zamiifolia": "zamioculcas-zamiifolia.JPG",
  "iridaceae-x-hollandica": "iridaceae-x-hollandica.jpg",
  "narcissus-spp.": "narcissus-spp..jpg",
  "brugmansia-x-candida": "brugmansia-x-candida.jpg",
  "hoya-kerrii": "hoya-kerrii.jpg",
  "calathea-roseopicta-'corona'": "calathea-roseopicta-'corona'.jpg",
  "peperomia-argyreia": "peperomia-argyreia.jpg",
  "adenium-obesum": "adenium-obesum.jpg",
  "cordyline-terminalis": "cordyline-terminalis.jpg",
  "tillandsia-cyanea": "tillandsia-cyanea.jpg",
  "kalanchoe-thyrsiflora": "kalanchoe-thyrsiflora.JPG",
  "ficus-elastica": "ficus-elastica.jpg",
  "pachystachys-lutea": "pachystachys-lutea.jpg",
  "allamanda-cathartica": "allamanda-cathartica.jpg",
  "crocus-hybrids": "crocus-hybrids.JPG",
  "fatsia-japonica": "fatsia-japonica.jpg",
  "hoya-carnosa": "hoya-carnosa.jpg",
  "rhipsalis-baccifera": "rhipsalis-baccifera.JPG",
  "begonia-x-hiemalis": "begonia-x-hiemalis.jpg",
  "sansevieria-cylindrica": "sansevieria-cylindrica.jpg",
  "helleborus-niger": "helleborus-niger.JPG",
  "pandanus-veitchii": "pandanus-veitchii.jpg",
  "oxalis-species": "oxalis-species.jpg",
  "pellaea-rotundifolia": "pellaea-rotundifolia.JPG",
  "nerium-oleander": "nerium-oleander.jpg",
  "musella-lasiocarpa": "musella-lasiocarpa.jpg",
  "alpinia-purpurata": "alpinia-purpurata.jpg",
  "plectranthus-hybrid": "plectranthus-hybrid.JPG",
  "callistemon-citrinus": "callistemon-citrinus.jpg",
  "trachycarpus-fortunei": "trachycarpus-fortunei.jpg",
  "primula-hybrids": "primula-hybrids.JPG",
  "acalypha-pendula": "acalypha-pendula.jpg",
  "echeveria-species": "echeveria-species.jpg",
  "begonia-hybrids": "begonia-hybrids.JPG",
}